Run unit tests in seperate job

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -44,11 +44,18 @@ jobs:
       - name: Start Weaviate
         run: ./test/start_containers.sh
       - name: Run tests
-        run: |
-          go test -v ./weaviate/...
-          ( for pkg in $(go list ./... | grep 'weaviate-go-client/v4/test'); do if ! go test -v -count 1 -race "$pkg"; then echo "Test for $pkg failed" >&2; false; exit; fi; done)
+        run: ( for pkg in $(go list ./... | grep 'weaviate-go-client/v4/test'); do if ! go test -v -count 1 -race "$pkg"; then echo "Test for $pkg failed" >&2; false; exit; fi; done)
       - name: Stop Weaviate
         run: ./test/stop_containers.sh
+  unit-tests:
+    - uses: actions/checkout@v3
+        - name: Set up Go
+          uses: actions/setup-go@v3
+          with:
+            go-version: 1.19
+            cache: true
+        - name: Run tests
+          run: go test -v ./weaviate/...
   tests-deprecated:
     runs-on: ubuntu-latest
     env:
